project:
  type: website
  output-dir: ../sawyerbelair.github.io

website:
  title: "Sawyer Belair's Blog"
  description: "Hot takes about the Denver Nuggets basketball club in the early 2020s."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sawyerbelair
      - icon: twitter
        href: https://twitter.com/snbelair
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

execute:
  freeze: auto 